server:
  port: 8082

spring:
  application:
       name: BookService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/online_library_project
    username: postgres
    password: 2907
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

